services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
      target: production

    env_file:
      - .env.production

    restart: on-failure

    ports:
      - '3000:3000'

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
