services:
  mongodb:
    image: bitnami/mongodb:8.0
    restart: on-failure

    environment:
      MONGODB_USERNAME: peacemaker
      MONGODB_PASSWORD: peacemaker-password
      MONGODB_ROOT_PASSWORD: my-secure-password
      MONGODB_DATABASE: peacemakerbot

    ports:
      - '27017:27017'

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

    volumes:
      - 'mongo_data:/bitnami/mongodb'

volumes:
  mongo_data:
    driver: local
